Fixing export_internal job

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -25,38 +25,37 @@ test_module:
 #     on release branches are never overwritten.  This behavior coincides
 #     with that of the external export job, where on the public pypi, packages
 #     cannot be overwritten.
-#   - main therefore only ever publishes '-dev' packages
-#   - The -dev package on main is always the newest version in the repository
+#   - master therefore only ever publishes '-dev' packages
+#   - The -dev package on master is always the newest version in the repository
 export_internal:
   stage: export
   image: python:3.7-slim
   script:
-    - apt -y update
-    - apt install -y --no-install-recommends wget
     - pip install -r requirements-dev.txt
     - python3 setup.py bdist_wheel --dist-dir=$CI_PROJECT_DIR/dist
     - VERSION=$(python3 -c "from imp import load_source; pkginfo = load_source('pkginfo.version', 'gtirb_types/version.py'); print(pkginfo.__version__)")
-    - if [[ "$VERSION" =~ \.dev[[:digit:]]*.*$ && "$CI_COMMIT_REF_NAME" =~ ^release-.* ]]; then exit 1; fi
+    - if [[ "$VERSION" =~ \.dev[[:digit:]]*.*$ && "$CI_COMMIT_REF_NAME" =~ ^release-.* ]]; then
+        echo "[ERROR] A development version cannot be exported to a release branch.";
+        exit 1;
+      fi
     # this job is not using $CI_JOB_TOKEN because it only has read access
     # https://gitlab.com/gitlab-org/gitlab/-/issues/35067
     # this job is also not using $CI_DEPLOY_USER and $CI_DEPLOY_PASSWORD because it only has write access
-    - if [[ "$CI_COMMIT_BRANCH" == "main" ]]; then
+    - if [[ "$CI_COMMIT_BRANCH" == "master" ]]; then
         if [[ ! "$VERSION" =~ \.dev[[:digit:]]*$ ]]; then
-          echo "[ERROR] On the main branch, we must be exporting a -dev version."
+          echo "[ERROR] On the master branch, we must be exporting a -dev version.";
           exit 1;
         fi;
         if pip3 install --index-url=$EXTRA_INDEX_URL --no-dependencies "gtirb_types>$VERSION" 2>/dev/null; then
-          echo "[ERROR] The package version being published on main should always be >= the version in the repository.";
+          echo "[ERROR] The package version in the repository cannot be more than the package version being published on master.";
           exit 1;
         fi;
-        wget ${CI_SERVER_HOST}/research/templates/python-module/raw/main/delete_remote_packages.py;
-        python3 $CI_PROJECT_DIR/delete_remote_packages.py $GL_PKG_API_TOKEN dist/*.whl;
+        ls $CI_PROJECT_DIR/dist/*.whl | xargs $CI_PROJECT_DIR/delete_remote_packages.py $GL_PKG_API_TOKEN;
       fi
-    - wget ${CI_SERVER_HOST}/research/templates/python-module/raw/main/.pypirc
     - sed "s/password = <access token>/password = $GL_PKG_API_TOKEN/" $CI_PROJECT_DIR/.pypirc > ~/.pypirc
     - python3 -m twine upload --verbose --repository repypi $CI_PROJECT_DIR/dist/*.whl
   tags:
     - kubernetes
   rules:
-    - if: '$CI_COMMIT_BRANCH == "main"'
+    - if: '$CI_COMMIT_BRANCH == "master"'
     - if: '$CI_COMMIT_REF_NAME =~ /^release-.*/'
